### ISSUE TITLE
Smith-Waterman exercise

### ISSUE THREAD

**Issue by EmanueleC** [Polpetta/Bioinformatic1#34]
**Description** Write the Smith-Waterman exercise in the appendix B

**Other issues**

**Comment by Polpetta** [comment]
Devo ancora provare a fare l'esercizio, per il momento la mergio perche' e' identata bene nel documento. Appena avro' tempo provo a fare l'esercizio e se non avro' lo stesso risultato apriremo una issue a parte @EmanueleC
