### ISSUE TITLE
Merge develop into master

### ISSUE THREAD

**Issue by mzanella** [Polpetta/Bioinformatic1#48]
**Description**
In `develop` branch there is much more work than in master. Can you merge those branches or there is some other stuff to do?

**Comment by Polpetta** [comment]
Eh, I dunno since a lot of time passed from my last contribution :sweat_smile: Honestly I don't remember what's in `develop` right now

**Comment by Polpetta** [comment]
@EmanueleC do you know why `develop` is ahead of `master`?
